version: '3'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - server
    ports:
      - 8080:80
    environment:
      PORT: ${PORT}

  server:
    build: ./server
    container_name: server
    depends_on:
      - mongo
    environment:
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_HOST_NAME: ${DB_HOST_NAME}
      DB_NAME: ${DB_NAME}
      ORIGIN: ${ORIGIN}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo/mongo-data:/data/db
    command:
      - mongod
